### ISSUE TITLE
Problem parsing LinkPickerList when using NestedContent

### ISSUE THREAD

**Issue by rpjengaard** [skybrud/Skybrud.LinkPicker#11]
Maybe the issue would be, that `data` param is allready a LinkPickerList and not a string - https://github.com/skybrud/Skybrud.LinkPicker/blob/master/src/Skybrud.LinkPicker/LinkPickerPropertyValueConverter.cs#L13

**Comment by abjerner** [comment]
@rpjengaard not sure whether this is still the case. Can you ping me if still is and is something that we should fix? (now that we're using Umbraco 8 instead).
