### ISSUE TITLE
Long links makes edit/delete buttons unreachable

### ISSUE THREAD

**Issue by rasmusfjord** [skybrud/Skybrud.LinkPicker#12]
The title says it all :)

![image](https://user-images.githubusercontent.com/1286043/54018263-7e30dd00-4188-11e9-9eed-53c7cf94eca2.png)

**Comment by abjerner** [comment]
This issue was fixed [**1.1.7**](https://github.com/skybrud/Skybrud.LinkPicker/releases/tag/v1.1.7) ;)
