### ISSUE TITLE
Hardcoded non-translatable Add-text

### ISSUE THREAD

**Issue by SonniTost** [skybrud/Skybrud.LinkPicker#13]
Skybrud.Umbraco.LinkPicker/Views/Editors/Link.html

Would be great if they could be translated without code alterations.

**Comment by abjerner** [comment]
Fixed in [**v2.0.0-alpha005**](https://github.com/skybrud/Skybrud.LinkPicker/releases/tag/v2.0.0-alpha005) 😉
