### ISSUE TITLE
Umbraco Version 8 support ?

### ISSUE THREAD

**Issue by stixoffire** [skybrud/Skybrud.LinkPicker#15]
Will this be updated for version 8 ?

**Comment by abjerner** [comment]
Hi @stixoffire,

Sorry for the lack of reply. You created this issue while I was on vacation, and have first had the time to catch up now 🌴 🌞 

We currently have a handful of alpha releases for Umbraco 8, but the Umbraco 8 version is very different from the Umbraco 7 version.

In the Umbraco 7 version, we have a property editor that represents a list of links, where each link item has the properties as implemented in the [`LinkPickerItem`](https://github.com/skybrud/Skybrud.LinkPicker/blob/dev-v7/src/Skybrud.LinkPicker/LinkPickerItem.cs) class.

This has served us well in the past, but it also made it very hard to create link items with other properties than the ones defined in the C# class. As a result of this, the Umbraco 8 package only provides a property editor for picking the link destination, but then also an Angular view for our [**Skybrud.Umbraco.Elements**](https://github.com/skybrud/Skybrud.Umbraco.Elements).

The **Skybrud.Umbraco.Elements** package allows developers to create lists of `IPublishedElement`, so it provides the flexibility of Umbraco 8's element types. The GIF below illustrates how one can set up a link item consisting of a property with the link destination as well as a property for the link text:

![link](https://user-images.githubusercontent.com/3634580/85072079-c70f7800-b1b8-11ea-98ae-b65f3741c5ac.gif)

Our **Skybrud.Umbraco.Elements** package is a bit similar to the new Block List Editor in Umbraco 8.7, so I'd imagine we'll also make some kind of Angular view enabling developers to set up link lists in with the Block List Editor.

I hope this answers your question 😉
