### ISSUE TITLE
Any plans to include Member to the LinkPicker?

### ISSUE THREAD

**Issue by akeilox** [skybrud/Skybrud.LinkPicker#4]
I came across this number of times but cant seem to find a picker with Member included.

Are there any plans to include member picker?

**Comment by abjerner** [comment]
@akeilox Can you tell some more about what you're trying to do? As members doesn't have a view or URL by default, I'm not sure how a member picker in the link picker would make sense.

Anyways, Umbraco comes with a build-in property editor for selecting (a single) member. Doesn't this do what you need, or do you need something more?
