### ISSUE TITLE
Problems with LeBlender

### ISSUE THREAD

**Issue by rpjengaard** [skybrud/Skybrud.LinkPicker#5]
Hi Bjerner,
i use Skybrud.LinkPicker 1.1.1. If i add a linkpicker datatype to LeBlender and use it on a gridelement, it will not save the data on the save event.

**Comment by abjerner** [comment]
Closing this as it was fixed in [v1.1.2](https://github.com/skybrud/Skybrud.LinkPicker/releases/tag/v1.1.2) (and @rpjengaard says it works).
