### ISSUE TITLE
Feature proposal - config nodetree

### ISSUE THREAD

**Issue by rpjengaard** [skybrud/Skybrud.LinkPicker#8]
It would be quite cool to have a config-option to control the content-tree. Like the xpath option in the MNTP. Ex. if i have a multisite solution, it would be cool to only see nodes from the current site (ex. $current/ancestor-or-self::*[@level = 2])

**Comment by abjerner** [comment]
This would require writing our own link picker dialog instead of using Umbraco dialog. As this is not feasible for now, I'm closing the issue 😉
